In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[4135, 6110, 2183, 9499],
 [4135, 6110, 2183, 4448],
 [4135, 6139, 2183, 7504],
 [5303, 8131, 9255, 3232, 3364],
 [5303, 8131, 9255, 3232, 600],
 [7452, 4135, 5261, 2183, 3403],
 [4051, 8049, 3514, 3232]]

In [10]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [11]:
import numpy as np

In [12]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4135 6110 2183 9499]
 [   0    0    0    0 4135 6110 2183 4448]
 [   0    0    0    0 4135 6139 2183 7504]
 [   0    0    0 5303 8131 9255 3232 3364]
 [   0    0    0 5303 8131 9255 3232  600]
 [   0    0    0 7452 4135 5261 2183 3403]
 [   0    0    0    0 4051 8049 3514 3232]]


In [13]:
## feature representation
dim=10

In [14]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

/home/sameer/DS-ML-NLP-Theory/ETE_DeepLear_Pro_Using Sim. RNN/venv/lib/python3.12/site-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(
2025-08-20 14:31:22.052111: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [15]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 875ms/step


array([[[ 0.01487784, -0.03985586,  0.0276651 , -0.01008181,
         -0.03526832,  0.00835873,  0.00744691, -0.02654507,
          0.04707428, -0.03760199],
        [ 0.01487784, -0.03985586,  0.0276651 , -0.01008181,
         -0.03526832,  0.00835873,  0.00744691, -0.02654507,
          0.04707428, -0.03760199],
        [ 0.01487784, -0.03985586,  0.0276651 , -0.01008181,
         -0.03526832,  0.00835873,  0.00744691, -0.02654507,
          0.04707428, -0.03760199],
        [ 0.01487784, -0.03985586,  0.0276651 , -0.01008181,
         -0.03526832,  0.00835873,  0.00744691, -0.02654507,
          0.04707428, -0.03760199],
        [ 0.0287703 , -0.03207153,  0.04654716,  0.03603301,
          0.00471889, -0.00538401,  0.00169963,  0.04241358,
         -0.04232985,  0.01718133],
        [-0.03501765, -0.02891293, -0.04616819,  0.00797924,
          0.01619078, -0.03634064, -0.01408726, -0.02453039,
          0.0242159 , -0.03829999],
        [ 0.02689617,  0.04540424,  0.01996298,  0.0

In [27]:
embedded_docs[0]

array([   0,    0,    0,    0, 4135, 6110, 2183, 9499], dtype=int32)